#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

const baseDir = __dirname;

// Simple glob function using Node's built-in fs
function globFiles(pattern, baseDir) {
	const results = [];
	function walk(dir) {
		if (!fs.existsSync(dir)) return;
		const files = fs.readdirSync(dir);
		for (const file of files) {
			const filePath = path.join(dir, file);
			const stat = fs.statSync(filePath);
			if (stat.isDirectory()) {
				walk(filePath);
			} else if (file.endsWith(".js")) {
				results.push(path.relative(baseDir, filePath).replace(/\\/g, "/"));
			}
		}
	}
	const fullPath = path.join(baseDir, pattern);
	if (fs.existsSync(fullPath)) {
		walk(fullPath);
	}
	return results.sort();
}

// Find all JS files in global, components, pages, and utils
const globalFiles = globFiles("js/0_global", baseDir);
const componentFiles = globFiles("js/2_components", baseDir);
const pageFiles = globFiles("js/3_pages", baseDir);
const utilFiles = globFiles("js/1_utils", baseDir);

// Read file content
function readFileContent(filePath) {
	const fullPath = path.join(baseDir, filePath);
	if (!fs.existsSync(fullPath)) return "";
	return fs.readFileSync(fullPath, "utf8");
}

// Build merged JS content
const buildMergedJS = () => {
	let content = "";

	// Header comment
	content += `// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY\n`;
	content += `// This file is automatically generated by build-js.js\n`;
	content += `// Run 'npm run dev:js' or 'npm run build:js' to regenerate\n\n`;

	// Wrap everything in IIFE to avoid global scope pollution
	content += `(function() {\n`;
	content += `  'use strict';\n\n`;

	// Global variables first (available to all other files)
	if (globalFiles.length > 0) {
		content += `  // ========================================\n`;
		content += `  // GLOBAL VARIABLES & CONFIGURATION\n`;
		content += `  // ========================================\n`;
		globalFiles.forEach((file) => {
			content += `  // From: ${file}\n`;
			content += readFileContent(file) + "\n\n";
		});
	}

	// Utility functions
	if (utilFiles.length > 0) {
		content += `  // ========================================\n`;
		content += `  // UTILITY FUNCTIONS\n`;
		content += `  // ========================================\n`;
		utilFiles.forEach((file) => {
			content += `  // From: ${file}\n`;
			content += readFileContent(file) + "\n\n";
		});
	}

	// Components
	if (componentFiles.length > 0) {
		content += `  // ========================================\n`;
		content += `  // COMPONENTS\n`;
		content += `  // ========================================\n`;
		componentFiles.forEach((file) => {
			content += `  // From: ${file}\n`;
			content += readFileContent(file) + "\n\n";
		});
	}

	// Pages (page-specific code)
	if (pageFiles.length > 0) {
		content += `  // ========================================\n`;
		content += `  // PAGE-SPECIFIC CODE\n`;
		content += `  // ========================================\n`;
		pageFiles.forEach((file) => {
			content += `  // From: ${file}\n`;
			content += readFileContent(file) + "\n\n";
		});
	}

	content += `})();\n`;

	return content;
};

// Generate main.js
const mainJsPath = path.join(baseDir, "dist/main.js");
const distDir = path.join(baseDir, "dist");

// Create dist directory if it doesn't exist
if (!fs.existsSync(distDir)) {
	fs.mkdirSync(distDir, { recursive: true });
}

const mergedContent = buildMergedJS();
fs.writeFileSync(mainJsPath, mergedContent);

console.log("✅ main.js generated successfully!");
console.log(`   🌍 Global: ${globalFiles.length}`);
console.log(`   🔧 Utils: ${utilFiles.length}`);
console.log(`   📦 Components: ${componentFiles.length}`);
console.log(`   📄 Pages: ${pageFiles.length}`);
console.log(`   📊 Total size: ${(mergedContent.length / 1024).toFixed(2)} KB`);
