#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

// Simple glob function using Node's built-in fs
function globFiles(pattern, baseDir) {
  const results = [];

  function walk(dir) {
    const files = fs.readdirSync(dir);

    for (const file of files) {
      const filePath = path.join(dir, file);
      const stat = fs.statSync(filePath);

      if (stat.isDirectory()) {
        walk(filePath);
      } else if (file.startsWith('_') && file.endsWith('.scss')) {
        results.push(path.relative(baseDir, filePath).replace(/\\/g, '/'));
      }
    }
  }

  const fullPath = path.join(baseDir, pattern);
  if (fs.existsSync(fullPath)) {
    walk(fullPath);
  }

  return results.sort();
}

// Paths
const baseDir = __dirname;
const scssDir = path.join(baseDir, 'scss');
const mainScssPath = path.join(scssDir, 'main.scss');

// Find all files in abstracts, base, components, layout, and pages
const abstractFiles = globFiles('scss/abstracts', baseDir);
const baseFiles = globFiles('scss/base', baseDir);
const componentFiles = globFiles('scss/components', baseDir);
const layoutFiles = globFiles('scss/layout', baseDir);
const pageFiles = globFiles('scss/pages', baseDir);

// Convert to import statements
const toImport = (filePath) => {
  return filePath
    .replace(/^scss\//, '')
    .replace(/\.scss$/, '')
    .replace(/\\/g, '/');
};

// Build main.scss content
const mainScssContent = `// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated by build-scss.js
// Run 'npm run dev' or 'npm run build' to regenerate

// Abstracts - Variables, mixins, functions (no CSS output, auto-imported)
${abstractFiles.length > 0 ? abstractFiles.map(f => `@import '${toImport(f)}';`).join('\n') : '// No abstracts found'}

// Base - Reset, typography, basic element styles (auto-imported)
${baseFiles.length > 0 ? baseFiles.map(f => `@import '${toImport(f)}';`).join('\n') : '// No base files found'}

// Components - Reusable UI components (auto-imported)
${componentFiles.length > 0 ? componentFiles.map(f => `@import '${toImport(f)}';`).join('\n') : '// No components found'}

// Layout - Layout sections (auto-imported)
${layoutFiles.length > 0 ? layoutFiles.map(f => `@import '${toImport(f)}';`).join('\n') : '// No layout files found'}

// Pages - Page-specific styles (auto-imported)
${pageFiles.length > 0 ? pageFiles.map(f => `@import '${toImport(f)}';`).join('\n') : '// No page files found'}
`;

// Write main.scss
fs.writeFileSync(mainScssPath, mainScssContent);

console.log('✅ main.scss generated successfully!');
console.log(`   🎨 Abstracts: ${abstractFiles.length}`);
console.log(`   📐 Base: ${baseFiles.length}`);
console.log(`   📦 Components: ${componentFiles.length}`);
console.log(`   🏗️  Layouts: ${layoutFiles.length}`);
console.log(`   📄 Pages: ${pageFiles.length}`);
